version: '3.9'
services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: password_db1206
      POSTGRES_DB: database_library

  library_offline:
    build: library_offline/
    restart: unless-stopped
    command: python manage.py runserver
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./library_offline/:/var/lib/
    depends_on:
      - db

  redis:
    image: "redis:5.0-alpine"

  worker:
    image: worker
    build:
      context: library_offline/library_offline/worker
      dockerfile: Dockerfile
    command: celery -A library_offline worker -l INFO
    depends_on:
      - redis





